run-dist:
	./build/install/app/bin/app
run-dist-version:
	./build/install/app/bin/app -V
run-dist-help:
	./build/install/app/bin/app -h
run-dist-files:
    .\app\build\install\app\bin\app .\app\file1.json .\app\file2.json

