run-dist:
	./build/install/app/bin/app
run-dist-version:
	./build/install/app/bin/app -V
run-dist-help:
	./build/install/app/bin/app -h
run-dist-files:
	./build/install/app/bin/app ./file1.json ./file2.json

